// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyChvMgqeuYFkowiZuSgS1uLhkeIeuk2hI8',
    appId: '1:102817731735:web:c3a47f226dfe47648605d2',
    messagingSenderId: '102817731735',
    projectId: 'marcapp-aac66',
    authDomain: 'marcapp-aac66.firebaseapp.com',
    databaseURL: 'https://marcapp-aac66-default-rtdb.asia-southeast1.firebasedatabase.app',
    storageBucket: 'marcapp-aac66.firebasestorage.app',
    measurementId: 'G-3MDDC4FV3X',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDxmYzNUAZ-2NKfL3nXC-hJxAIlF2hSGIs',
    appId: '1:102817731735:android:c2fb9abdf27607708605d2',
    messagingSenderId: '102817731735',
    projectId: 'marcapp-aac66',
    databaseURL: 'https://marcapp-aac66-default-rtdb.asia-southeast1.firebasedatabase.app',
    storageBucket: 'marcapp-aac66.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAAHbHpYS5ytt6fbPfg0vRLD4kIvBEht_c',
    appId: '1:102817731735:ios:95de287596f06e748605d2',
    messagingSenderId: '102817731735',
    projectId: 'marcapp-aac66',
    databaseURL: 'https://marcapp-aac66-default-rtdb.asia-southeast1.firebasedatabase.app',
    storageBucket: 'marcapp-aac66.firebasestorage.app',
    iosBundleId: 'com.example.marcapp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAAHbHpYS5ytt6fbPfg0vRLD4kIvBEht_c',
    appId: '1:102817731735:ios:95de287596f06e748605d2',
    messagingSenderId: '102817731735',
    projectId: 'marcapp-aac66',
    databaseURL: 'https://marcapp-aac66-default-rtdb.asia-southeast1.firebasedatabase.app',
    storageBucket: 'marcapp-aac66.firebasestorage.app',
    iosBundleId: 'com.example.marcapp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyChvMgqeuYFkowiZuSgS1uLhkeIeuk2hI8',
    appId: '1:102817731735:web:82e2a7f77dff98df8605d2',
    messagingSenderId: '102817731735',
    projectId: 'marcapp-aac66',
    authDomain: 'marcapp-aac66.firebaseapp.com',
    databaseURL: 'https://marcapp-aac66-default-rtdb.asia-southeast1.firebasedatabase.app',
    storageBucket: 'marcapp-aac66.firebasestorage.app',
    measurementId: 'G-TSK8HMR6NH',
  );
}
